# Use the latest version of Ubuntu as the base image
FROM ubuntu:latest

# Update the list of available packages
RUN apt-get update

# Upgrade the installed packages
RUN apt-get upgrade -y

# Command to run when a container is started from this image
CMD echo "Hello, World!"
